swagger: "2.0"
info:
  description: This is a project to querying hills using various criteria
  version: 1.0.0
  title: Hills Query Service
basePath: /v1
schemes:
  - http
paths:
  /hills:
    get:
      summary: Find matching hills corresponding to query
      description: Find matching hills corresponding to query
      operationId: getHillsInfo
      produces:
        - application/json
      parameters:
        - name: category
          in: query
          description: Hill category
          required: false
          type: "array"
          items:
            type: "string"
            enum:
              - MUN
              - TOP
        - name: sortBy
          in: query
          description: Sort criteria
          required: false
          type: "array"
          items:
            type: "string"
            enum:
              - HEIGHT
              - NAME
        - name: order
          in: query
          description: Ascending or descending order
          required: false
          type: "string"
          enum:
            - ASC
            - DESC
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Hill"

definitions:
  Hill:
    type: object
    properties:
      name:
        type: string
        description: Name of the hill
      height:
        type: number
        description: Height of the hill
      category:
        type: string
        description: Hill Category
      grid_ref:
        type: string
        description: Grid reference
